services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    restart: always
    ports:
      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userdb
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: userpass
    depends_on:
      - mysql

  enrollment-service:
    build: ./enrollment-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  course-service:
    build: ./course-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  upload-grade-service:
    build: ./upload-grade-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql

  view-grade-service:
    build: ./view-grade-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql

  view-service:
    build: ./viewservice
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
